---

variables:
  JDK_VERSION: '8u322-b06'
  JDK_HASH: '3d62362a78c9412766471b05253507a4cfc212daea5cdf122860173ce902400e'

stages:
  - build

build:
  only:
    - tags
  stage: build
  image: debian:bullseye
  script: |
    set -eux
    apt-get update
    apt-get -y upgrade
    apt-get -y install git wget
    v=$(echo "${JDK_VERSION}" | tr -d '-')
    wget "https://github.com/adoptium/temurin8-binaries/releases/download/jdk${JDK_VERSION}/OpenJDK8U-jdk_x64_linux_hotspot_${v}.tar.gz"
    [ "X${JDK_HASH}" = X$(sha256sum OpenJDK* | awk '{print $1;}') ]
    gzip -cd Open* | tar -f- -x
    PATH="$(pwd)/jdk${JDK_VERSION}/bin:${PATH}"
    export PATH
    
    # https://github.com/gradle/gradle/issues/3117
    env -i PATH="${PATH}" ./gradlew build -x test
    mv ./releases/* ..
    cd -
    rm -rf ./jdk* ./Open* ./CollaboratorPlusPlus
  artifacts:
    untracked: true
